name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Print goodbye
        run: echo "Done - bye"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Max
        run: echo "Hello Max"
      - name: Greet John
        run: echo "hello John"
      - name: Greet Tim
        run: echo "hello Tim"
  
  
